### ISSUE TITLE
Optional typings

### ISSUE THREAD

**Issue by LukeHankey** [Bot-detector/Bot-Detector-Core-Files#252]
I saw the python version is now at 3.10 from the docker files and the [recommended](https://stackoverflow.com/questions/69440494/python-3-10-optionaltype-or-type-none) way for Optional types is now `type | None` in lieu of `Optional[type]`.

Slight nit pick.

**Comment by Ferrariic** [comment]
Thanks! I'll look at making the relevant changes :)

**Comment by Ferrariic** [comment]
Attempted to implement, ran into an issue with pydantic - https://github.com/samuelcolvin/pydantic/issues/3300

For future, patch here: https://github.com/samuelcolvin/pydantic/issues/3300#issuecomment-950122191

I'll wait until a full pydantic patch is available and the issue is closed prior to changing type. In the meantime I'll keep this issue open - if it doesn't happen any time soon I may implement the patch.
