### ISSUE TITLE
add black formatting to github actions

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/Bot-Detector-Core-Files#461]
code should be formatted with python black

**Comment by LukeHankey** [comment]
Id recommend adding pre-commit as a whole instead of individual workflows to GHA. This allows you to just update the pre-commit config file with any new tools that are used for the project, such as flake8 or import sorting. Pre-commit can also run before committing, hence the name, which should catch any issues first.

**Comment by ThorntonMatthewD** [comment]
+1 for pre-commit hooks

https://user-images.githubusercontent.com/44626690/187330661-92a855f9-9015-4dca-b04e-9d79fd6f495e.mp4

**Comment by LukeHankey** [comment]
The only step that wouldn't be automatic is the first command. You don't have to run `pre-commit run` as that would run automatically when creating a new commit

**Comment by extreme4all** [comment]
@LukeHankey sure sounds good then, can we also use the pylintrc found in https://google.github.io/styleguide/pyguide.html, with a few modifications?

**Comment by LukeHankey** [comment]
Yup. https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html

**Comment by extreme4all** [comment]
@LukeHankey , @ThorntonMatthewD couldn't commit with precommit. this also requires local instalation.
just python black on PR, that tells you what files & lines do not pass the linting would be perfect
